spring:
  application:
    name: artgallery
  mongodb:
    uri: mongodb://localhost:27017/artgallery
    auto-index-creation: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-artgallery.au.auth0.com/

auth0:
  audience: https://artgallery-backend/

server:
  servlet:
    context-path: /api
